### ISSUE TITLE
Create Users Login

### ISSUE THREAD

**Issue by XanderStrike** [XanderStrike/SBSG#2]
Let the user log in. Each user gets a row in the "businesses" table, so "businesses" could be considered the "users" table. You can replace it with a "users" table if you like, I just had it this way so we could eventually allow multiple businesses per user.

**Comment by d-ray** [comment]
Are there potentially multiple users per business?  Like maybe if assistant managers need access to this as well?

**Comment by XanderStrike** [comment]
Not at this point. I think we can just do one account per business (and one business per account) for now, if managers want to have other people use their account they can just give them the password.

**Comment by d-ray** [comment]
You got it boss
