### ISSUE TITLE
Time selects could be improved

### ISSUE THREAD

**Issue by XanderStrike** [XanderStrike/SBSG#9]
Right now we're just using the default time input that rails provides which is crap (dropdown with 60 numbers? hell no). We should probably find a better way to do this, I think maybe having just number fields (with maybe AM/PM radio buttons).

Inspiration: http://i.imgur.com/kjKHj.png

**Comment by d-ray** [comment]
Time selects now use am/pm in the hour field and are limited to 15 minute increments in the minutes field
